---
#used in Jenkins pipelines as the persistent storage for the build containers
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-slave-{{counter}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{STORAGE_CLASS_NAME}}