kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: pure-file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-jenkins-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: pure-file