---
#used in Jenkins pipelines as the persistent storage for the build containers
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-jenkins-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: pure-file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fa-jenkins-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: pure-block
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-jenkins-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: kontena-storage-block

