---
#used in Jenkins pipelines as the persistent storage for the build containers
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-jenkins-slave-{{counter}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: pure-file