kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-jenkins
{{IMPORT_VOLUMES_COMMENT}}  annotations:
{{IMPORT_VOLUMES_COMMENT}}    import.volume.beta.purestorage.com/name: cicd-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{STORAGE_CLASS_NAME}}
---
#used in Jenkins pipelines as the persistent storage for the build containers
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-jenkins-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pure-file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fa-jenkins-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pure-block