kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-jenkins
{{IMPORT_VOLUMES_COMMENT}}  annotations:
{{IMPORT_VOLUMES_COMMENT}}    import.volume.beta.purestorage.com/name: cicd-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{STORAGE_CLASS_NAME}}