apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira
      name: jira
    spec:
      containers:
        - name: jira
          image: cptactionhank/atlassian-jira-software:7.9.1
          resources:
            requests:
              memory: 10G
          volumeMounts:
            - name: jira-home
              mountPath: /var/atlassian/jira
      volumes:
        - name: jira-home
          persistentVolumeClaim:
            claimName: fb-jira