apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira-service
  name: jira-service
spec:
  type: 
  ports:
    - port: 8083
      targetPort: 8080
  selector:
    app: jira
  externalIPs:
  - 10.21.236.86