apiVersion: v1
kind: Service
metadata:
  name: {{template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
{{- if .Values.Master.ServiceAnnotations }}
  annotations:
{{ toYaml .Values.Master.ServiceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - port: {{.Values.Master.ServicePort}}
      name: http
      targetPort: {{.Values.Master.ContainerPort}}
      {{if (and (eq .Values.Master.ServiceType "NodePort") (not (empty .Values.Master.NodePort)))}}
      nodePort: {{.Values.Master.NodePort}}
      {{end}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
  type: {{.Values.Master.ServiceType}}
  {{if not (empty .Values.Master.ExternalIP)}}
  externalIPs:
  - {{.Values.Master.ExternalIP}}
  {{end}}
