apiVersion: v1
kind: Service
metadata:
  name: pure-gitlab-new-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    app: unicorn
    release: pure-gitlab-new