VAGRANT_INSTANCE_NAME = "pure-storage-vm"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
    
    config.vm.box               = "atlas_shrugged/vsphere_dummy"
    config.vm.box_version       = "1.0.0"
    config.ssh.username         = "root"
    config.ssh.private_key_path = "./pkey"
    config.vm.provision :shell, path: "bootstrap.sh", run: 'always'
    
    
    (1..NODE_COUNT).each do |i|
        config.vm.define VAGRANT_INSTANCE_NAME+"#{i}" do |d|
            d.vm.hostname = VAGRANT_INSTANCE_NAME+"#{i}"
        end
    end    
 
    config.vm.provider :vsphere do |vsphere|
        vsphere.host                  = '10.21.236.254'
        # vsphere.name                = VAGRANT_INSTANCE_NAME+"#{i}"
        vsphere.compute_resource_name = 'DevOps-Cluster'
        vsphere.template_name         = 'perf-vm-new'
        vsphere.vm_base_path          = "kernel"
        vsphere.user                  = 'Administrator@vsphere.local'
        vsphere.password              = 'Osmium76$'
        vsphere.insecure              = true
    end
    
end