apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  labels:
    k8s-app: nginx-ingress-lb
  name: ingress-nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer