kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-nexus
  annotations:
    import.volume.beta.purestorage.com/name: cicd-nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{STORAGE_CLASS_NAME}}