apiVersion: v1
kind: Service
metadata:
  name: pure-nexus
spec:
  type: 
  ports:
  - port: {{NEXUS_PORT}}
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 5000
    targetPort: {{DOCKER_REGISTRY_PORT}}
    protocol: TCP
    name: docker 
  selector:
    app: nexus
  externalIPs:
  - {{NEXUS_IP_ADDRESS}}