kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: pure-file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-gitlab-etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: pure-file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-gitlab-redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: pure-file
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fb-gitlab-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: pure-file

