kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: {{STORAGE_CLASS_NAME}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-gitlab-etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: {{STORAGE_CLASS_NAME}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-gitlab-redis
spec:
  accessModes:
    - {{PV_ACCESS_MODE}}
  resources:
    requests:
      storage: 300Gi
  storageClassName: {{STORAGE_CLASS_NAME}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-gitlab-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: {{STORAGE_CLASS_NAME}}

