FROM jenkinsci/jnlp-slave
MAINTAINER Ashutosh Kumar akumar@purestorage.com
USER root
RUN apt-get -o Acquire::ForceIPv4=true -y update && apt-get -o Acquire::ForceIPv4=true -y install sudo && apt-get clean
RUN adduser jenkins sudo
RUN passwd -d jenkins
USER jenkins